export const GameComponents = [
  {
     "id":"alchimie",
     "class":"alchimie",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Alchimie",
     "type":"magicItem"
  },
  {
     "id":"alchimiste",
     "class":"alchimiste",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Alchimiste",
     "type":"mage"
  },
  {
     "id":"anneauDeMidas",
     "class":"anneau_de_midas",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Anneau de Midas",
     "type":"artefact"
  },
  {
     "id":"arbreDeVie",
     "class":"arbre_de_vie",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Arbre de vie",
     "type":"artefact"
  },
  {
     "id":"arcElfique",
     "class":"arc_elfique",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Arc Elfique",
     "type":"artefact"
  },
  {
     "id":"artificier",
     "class":"artificier",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Artificier",
     "type":"mage"
  },
  {
     "id":"athanor",
     "class":"athanor",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Athanor",
     "type":"artefact"
  },
  {
     "id":"autelCorrompu",
     "class":"autel_corrompu",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Autel Corrompu",
     "type":"artefact"
  },
  {
     "id":"automate",
     "class":"automate",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Automate",
     "type":"artefact"
  },
  {
     "id":"bestiaireDuSorcier",
     "class":"bestiaire_du_sorcier",
     "excludedComponentId":"repaireDesDragons",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Bestiaire du Sorcier",
     "type":"placeOfPower"
  },
  {
     "id":"bibliotheque",
     "class":"bibliotheque",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Bibliothèque",
     "type":"monument"
  },
  {
     "id":"bosquetSacre",
     "class":"bosquet_sacre",
     "excludedComponentId":"tourDeLAlchimiste",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Bosquet Sacré",
     "type":"placeOfPower"
  },
  {
     "id":"caliceDeVie",
     "class":"calice_de_vie",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Calice de Vie",
     "type":"artefact"
  },
  {
     "id":"catacombesDeLaMort",
     "class":"catacombes_de_la_mort",
     "excludedComponentId":"puitsSacrificiel",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Catacombes de la Mort",
     "type":"placeOfPower"
  },
  {
     "id":"coffreFort",
     "class":"coffre_fort",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Coffre Fort",
     "type":"artefact"
  },
  {
     "id":"colosse",
     "class":"colosse",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Colosse",
     "type":"monument"
  },
  {
     "id":"corneDAbondance",
     "class":"corne_d_abondance",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Corne d'Abondance",
     "type":"artefact"
  },
  {
     "id":"coupeDeFeu",
     "class":"coupe_de_feu",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Coupe de Feu",
     "type":"artefact"
  },
  {
     "id":"craneMaudit",
     "class":"crane_maudit",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Crâne Maudit",
     "type":"artefact"
  },
  {
     "id":"crypte",
     "class":"crypte",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Crypte",
     "type":"artefact"
  },
  {
     "id":"dagueSacrificielle",
     "class":"dague_sacrificielle",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Dague Sacrificielle",
     "type":"artefact"
  },
  {
     "id":"dentDeDragon",
     "class":"dent_de_dragon",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Dent de dragon",
     "type":"artefact"
  },
  {
     "id":"divination",
     "class":"divination",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Divination",
     "type":"magicItem"
  },
  {
     "id":"dragonDOs",
     "class":"dragon_d_os",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Dragon d'Os",
     "type":"artefact"
  },
  {
     "id":"dragonDeFeu",
     "class":"dragon_de_feu",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Dragon de Feu",
     "type":"artefact"
  },
  {
     "id":"dragonDeTerre",
     "class":"dragon_de_terre",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Dragon de Terre",
     "type":"artefact"
  },
  {
     "id":"dragonDesEaux",
     "class":"dragon_des_eaux",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Dragon des Eaux",
     "type":"artefact"
  },
  {
     "id":"dragonDesVents",
     "class":"dragon_des_vents",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Dragon des Vents",
     "type":"artefact"
  },
  {
     "id":"druidesse",
     "class":"druidesse",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Druidesse",
     "type":"mage"
  },
  {
     "id":"duelliste",
     "class":"duelliste",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Duelliste",
     "type":"mage"
  },
  {
     "id":"eclatElementaire",
     "class":"eclat_elementaire",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Éclat Élémentaire",
     "type":"artefact"
  },
  {
     "id":"epeeVive",
     "class":"epee_vive",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Épée Vive",
     "type":"artefact"
  },
  {
     "id":"erudit",
     "class":"erudit",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Érudit",
     "type":"mage"
  },
  {
     "id":"etangDeSerenite",
     "class":"etang_de_serenite",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Étang de Sérénité",
     "type":"artefact"
  },
  {
     "id":"faucon",
     "class":"faucon",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Faucon",
     "type":"artefact"
  },
  {
     "id":"fontaineDeJouvence",
     "class":"fontaine_de_jouvence",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Fontaine de Jouvence",
     "type":"artefact"
  },
  {
     "id":"forgeMaudite",
     "class":"forge_maudite",
     "excludedComponentId":"mineDesNains",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Forge Maudite",
     "type":"placeOfPower"
  },
  {
     "id":"fouetArdent",
     "class":"fouet_ardent",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Fouet Ardent",
     "type":"artefact"
  },
  {
     "id":"grandePyramide",
     "class":"grande_pyramide",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Grande Pyramide",
     "type":"monument"
  },
  {
     "id":"guerisseur",
     "class":"guerisseur",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Guérisseur",
     "type":"mage"
  },
  {
     "id":"harnaisDuDragon",
     "class":"harnais_du_dragon",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Harnais du Dragon",
     "type":"artefact"
  },
  {
     "id":"jardinsSuspendus",
     "class":"jardins_suspendus",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Jardins Suspendus",
     "type":"monument"
  },
  {
     "id":"mainDeGloire",
     "class":"main_de_gloire",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Main de Gloire",
     "type":"artefact"
  },
  {
     "id":"manoirDeCorail",
     "class":"manoir_de_corail",
     "excludedComponentId":"recifDesNaufrageurs",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Manoir de Corail",
     "type":"placeOfPower"
  },
  {
     "id":"mausolee",
     "class":"mausolee",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Mausolée",
     "type":"monument"
  },
  {
     "id":"mineDeSalomon",
     "class":"mine_de_salomon",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Mine de Salomon",
     "type":"monument"
  },
  {
     "id":"mineDesNains",
     "class":"mine_des_nains",
     "excludedComponentId":"forgeMaudite",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Mine des Nains",
     "type":"placeOfPower"
  },
  {
     "id":"molosse",
     "class":"molosse",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Molosse",
     "type":"artefact"
  },
  {
     "id":"montureCeleste",
     "class":"monture_celeste",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Monture Céleste",
     "type":"artefact"
  },
  {
     "id":"mortVie",
     "class":"mort_vie",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Mort Vie",
     "type":"magicItem"
  },
  {
     "id":"necromancienne",
     "class":"necromancienne",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Nécromancienne",
     "type":"mage"
  },
  {
     "id":"obelisque",
     "class":"obelisque",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Obélisque",
     "type":"monument"
  },
  {
     "id":"oeufDeDragon",
     "class":"oeuf_de_dragon",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Oeuf de Dragon",
     "type":"artefact"
  },
  {
     "id":"oracle",
     "class":"oracle",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Oracle",
     "type":"monument"
  },
  {
     "id":"pierrePhilosophale",
     "class":"pierre_philosophale",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Pierre Philosophale",
     "type":"artefact"
  },
  {
     "id":"piocheDesNains",
     "class":"pioche_des_nains",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Pioche des Nains",
     "type":"artefact"
  },
  {
     "id":"prisme",
     "class":"prisme",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Prisme",
     "type":"artefact"
  },
  {
     "id":"protection",
     "class":"protection",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Protection",
     "type":"magicItem"
  },
  {
     "id":"puitsCalcifere",
     "class":"puits_calcifere",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Puits Calcifère",
     "type":"artefact"
  },
  {
     "id":"puitsSacrificiel",
     "class":"puits_sacrificiel",
     "excludedComponentId":"catacombesDeLaMort",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Puits Sacrificiel",
     "type":"placeOfPower"
  },
  {
     "id":"reanimation",
     "class":"reanimation",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Réanimation",
     "type":"magicItem"
  },
  {
     "id":"recherches",
     "class":"recherches",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Recherches",
     "type":"magicItem"
  },
  {
     "id":"recifDesNaufrageurs",
     "class":"recif_des_naufrageurs",
     "excludedComponentId":"manoirDeCorail",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Récif des Naufrageurs",
     "type":"placeOfPower"
  },
  {
     "id":"repaireDesDragons",
     "class":"repaire_des_dragons",
     "excludedComponentId":"bestiaireDuSorcier",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Repaire des dragons",
     "type":"placeOfPower"
  },
  {
     "id":"rossignol",
     "class":"rossignol",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Rossignol",
     "type":"artefact"
  },
  {
     "id":"sereniteVigueur",
     "class":"serenite_vigueur",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Sérénité Vigueur",
     "type":"magicItem"
  },
  {
     "id":"serpentDeMer",
     "class":"serpent_de_mer",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Serpent de Mer",
     "type":"artefact"
  },
  {
     "id":"sirene",
     "class":"sirene",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Sirène",
     "type":"artefact"
  },
  {
     "id":"sorciere",
     "class":"sorciere",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Sorcière",
     "type":"mage"
  },
  {
     "id":"sourceElementaire",
     "class":"source_elementaire",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Source Élémentaire",
     "type":"artefact"
  },
  {
     "id":"statueSacree",
     "class":"statue_sacree",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Statue Sacrée",
     "type":"monument"
  },
  {
     "id":"statuetteOrnee",
     "class":"statuette_ornee",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Statuette Ornée",
     "type":"artefact"
  },
  {
     "id":"temple",
     "class":"temple",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Temple",
     "type":"monument"
  },
  {
     "id":"tourDeLAlchimiste",
     "class":"tour_de_l_alchimiste",
     "excludedComponentId":"bosquetSacre",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Tour de l'Alchimiste",
     "type":"placeOfPower"
  },
  {
     "id":"transmutation",
     "class":"transmutation",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Transmutation",
     "type":"magicItem"
  },
  {
     "id":"transmutatrice",
     "class":"transmutatrice",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Transmutatrice",
     "type":"mage"
  },
  {
     "id":"treant",
     "class":"treant",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Tréant",
     "type":"artefact"
  },
  {
     "id":"voyante",
     "class":"voyante",
     "hasSpecificCollectAbility":false,
     "hasStandardCollectAbility":false,
     "isCreature":false,
     "isDragon":false,
     "name":"Voyante",
     "type":"mage"
  }
]